make HTTP call to /live to determine if emulator is fully up
onflow/flow-js-testing pull request #73
Opened 2022-01-10 16:37 UTC by kerrywei

## Description
Change the way flow-js-testing detects emulator status: from reading emulator logging to making an API call to /live endpoint

## tests
- create a simple test project, verified tests are working there 
- introduce long delay in emulator startup, verified tests are working
- introduce long delay in emulator startup, set a short timeout for tests, verify test will fail due to timeout

______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-js-testing/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

2022-01-10 17:09 UTC, kerrywei commented
> @kerrywei what version of CLI we need to enable this?

current latest version is good enough, that /live endpoint has been there for a while. once Gregor implemented all RESTful APIs including the /ping API, we can switch to the /ping API, which is more official

2022-01-11 15:51 UTC, MaxStalker commented on src/emulator.js
> +        const url = "http://localhost:" + port + "/live"
We can string template literals here: 
```suggestion
        const url = `http://localhost:${port}/live`
```

2022-01-11 15:51 UTC, MaxStalker commented on src/emulator.js
> +        http.get(url, (resp) => {
I think we can simply use `fetch` here instead of a `http.get` - but this will do as well.
We can refactor it later :)

2022-01-11 17:34 UTC, MaxStalker approved these changes

2022-01-11 21:01 UTC, MaxStalker requested changes

2022-01-11 21:01 UTC, MaxStalker commented on src/emulator.js
> +import * as sdk from "@onflow/sdk";
We don't have `@onflow/sdk` dependency :)

2022-01-11 21:01 UTC, MaxStalker commented on src/emulator.js
> +          ])).then(sdk.decode);
```suggestion
          await fcl.send(fcl.build([
            fcl.getBlock(false)
          ])).then(fcl.decode);
```

2022-01-11 21:03 UTC, kerrywei commented on src/emulator.js
> +import * as sdk from "@onflow/sdk";
👍  good callout -- both addressed

2022-01-11 21:17 UTC, MaxStalker commented on src/emulator.js
> +import * as fcl from "@onflow/fcl";
```suggestion
import { send, build, getBlock, decode } from "@onflow/fcl";
```

2022-01-11 21:17 UTC, MaxStalker commented on src/emulator.js
> +          ])).then(fcl.decode);
```suggestion
          await send(build([ getBlock(false) ])).then(decode);
```

2022-01-11 21:17 UTC, MaxStalker commented on src/emulator.js
> +import * as fcl from "@onflow/fcl";
We can import only methods we need. Then transpiler can `tree-shake` what is not necessary (we are not using all of the methods from `@onflow/fcl`) :)

2022-01-11 21:23 UTC, MaxStalker approved these changes
Looks good :)

2022-01-12 19:49 UTC, merged

2022-01-12 19:54 UTC, kerrywei commented
merge in the solution to get it further vetted by the community. I run the pipeline 42 times, all succeeded with any failures